use master

go



create database HomestayBooking

go 

use HomestayBooking

go 

create table Customer( 
CustomerID int IDENTITY(1,1) primary key, 
[Name] nvarchar(30) not null,
Gender bit,
DOB date, 
Phone nvarchar(10) check (Phone not like '%[^0-9]%' and len(Phone)>=8 and len(Phone)<=10), 
Email nvarchar(MAX),
);

create table Account(
username nvarchar(50) primary key,
[password] nvarchar(50) not null,
[Type] bit,
CustomerID int references Customer(CustomerID), 
)

create table HomestayType(
TypeID int IDENTITY(1,1) primary key,
[Name] nvarchar(MAX),
Acreage int,
Rooms int,
Beds int,
Bathrooms int,
Capacity int,
Price float,
);

create table Homestay(
HomestayID int IDENTITY(1,1) primary key,
[Name] nvarchar(MAX),
[Address] nvarchar(MAX),
TypeID int references HomestayType(TypeID),
[Description] nvarchar(MAX),
[Image] nvarchar(MAX),
);

create table Booking(
BookingID int IDENTITY(1,1) primary key,
CustomerID int references Customer(CustomerID), 
HomestayID int references Homestay(HomestayID),
[Date] date,
DateFrom date,
DateTo date,
NumberOfPeople int,
TotalPrice float,
);
-- insert data into database
INSERT INTO [dbo].[HomestayType]
           ([Name]
           ,[Acreage]
           ,[Rooms]
           ,[Beds]
           ,[Bathrooms]
           ,[Capacity]
           ,[Price])
VALUES
('Log Cabin',15,1,1,1,2,15),
('Apartment',20,1,1,1,2,20),
('Homestay',35,1,4,1,4,40),
('Studio',40,1,2,1,4,30),
('Hotel',50,1,2,1,4,50),
('Penthouse',70,2,2,1,6,60),
('Condominium',100,2,2,2,6,70),
('Entire House',270,4,6,3,12,100),
('Villa',350,5,9,4,20,150),
('Resort',400,6,10,4,30,200)
GO

INSERT INTO [dbo].[Homestay]
           ([Name]
           ,[Address]
           ,[TypeID]
           ,[Description]
           ,[Image])
VALUES
('Ha Noi Home 3', 'Tay Ho, Ha Noi, Viet Nam', 2, 'The apartment is located in an ideal location, this place is a crowded street of the foreign community. There are many restaurants, bars, cafes, gyms, all made for foreigners. The surrounding area has many beautiful landscapes such as Ho Kiem, Ho Truc Bach, Quan Thanh Pagoda, Red River, Quang An Flower Village, Nhat Tan Flower Village and especially large and large West Lake, where you can go. Bicycles (free of charge) around the lake and coffee along the way. Contrary to the bustle of the street, the apartment is located in an alley about 100 meters from the street, very quiet and suitable for rest, work and live here. You will feel comfortable because the Host is very friendly and hospitable. Safe house with 24/24 security. You can enjoy cycling around town with free bicycles. Free housekeeping service twice a week, parking motorbike in the building.','images/homestay/hanoi1.jpg'),
('Indochina Style Duplex', 'Tay Ho, Ha Noi, Viet Nam', 8, 'Welcome to MLIBRARY - The most luxurious apartment experience in Hanoi. MLIBRARY bring you the style that hasn’t been seen anywhere in Vietnam. Located in Tay Ho district with enormous view of West Lake and The Red River. “ We do not build a homestay, we develop a living space with a lot of emotion”', 'images/homestay/hanoi2.jpg'),
('King’s Apartment', 'Tay Ho, Ha Noi, Viet Nam', 4, 'Located in the quiet Xuan Dieu Street, 500m from West Lake, King’s Apartment offers fully furnished Studio rooms such as kitchen, TV, refrigerator, dryer, air conditioner, private bathroom and free wifi. Convenient traffic location is 21 km from the airport, about 4 km from the old town and Dong Xuan market. Guests can enjoy free access to street, European and Asian dishes around King’s Apartment area.', 'images/homestay/hanoi3.jpg'),
('BHA - R1 - Executive', 'Cau Giay, Ha Noi, Viet Nam', 2, 'Located at No.18, Dich Vong Hau Street in the center of Cau Giay District where is a new modern urban of Hanoi, it would be pretty convenient for you to approach the hotel from where you are. With 45 well-equipped & fully furnished rooms, Bao Hung Hotel & Apartment is now one of the biggest in Cau Giay district.', 'images/homestay/hanoi4.jpg'),
('Lii’s Homestay','Tay Ho, Ha Noi, Viet Nam', 3, 'Lii’s Homestay is a homestay located in the heart of Hanoi, next to the West Lake. Lii’s Homestay aims to the natural elements in the living space, we always take care of every smallest decor in the room. We take care of our customers like family members. Lii’s Homestay is very quiet. Just 5 minutes away, you will reach West Lake. Come to us today.', 'images/homestay/hanoi5.jpg'),
('Mango treehouse', 'Ba Vi, Ha Noi, Viet Nam', 8, 'Does the bustling city drive you nuts sometimes? Do you feel short of me-time? Longing for new energy? Wondering what is life on a tree with leaves and bees? We offer you the OKia Treehouse for a wonderful get-away trip & all the best thrills nature can bring. Only 40 minutes drive from Hanoi, your family, your kids or your group of friends will reach the Treehouse. Here we proudly bring you very personalized experience so you can get all the “sensory” that you need for a better “you” or a better relationship with your buddies. OKia Treehouse is an invitation to self-soothe and to bring people closer – what is really important in this “fast-food” world.', 'images/homestay/hanoi6.png'),
('Vinhomes GreenBay','Nam Tu Liem, Ha Noi, Viet Nam', 7, 'New and modern apartment’s just furnished with conveniences to help customers feel like home. The whole apartment is full of natural light, creating both airy and spacious. The buildings has full amenities includes Gym, 4 season swimming pool, nice garden, restaurants, kid play areas, Pharmacy shop... Traffic is very convenient to go anywhere in the city as well as industrial parks around the capital Ha Noi.', 'images/homestay/hanoi7.jpg'),
('Zen Mediation House', 'Long Bien, Ha Noi, Viet Nam', 7, 'Pictures speak a thousands words. This beautiful and unique Tree House is among one of Seven Wonder Houses built by artist Dao Anh Khanh - a leading Vietnamese Artist, known for his famous dance performance and contemporary arts. ', 'images/homestay/hanoi8.jpg'),
('Beca Homestay', 'Hai Ba Trung, Ha Noi, Viet Nam', 2, 'A well-equipped room located on Hanoi’s famous central street, 1 km from Hoan Kiem Lake. Lots of best restaurants and famous food around here. Its also very close to Vincom Center-the most famous shopping. You just need to walk. There is a nice balcony for you to enjoy tea or coffee every morning and a romantic dinner with friends. Would be a great experience with city view.', 'images/homestay/hanoi9.jpg'),
('Cloudy View', 'Ba Vi, Ha Noi, Viet Nam', 9, 'Leaving the noisy and crowded city to find a private living space that is airy, peaceful in the water, plants and sunshine with CLOUDY VIEW - Ba Vi. With a modern swimming pool, overlooking the green tea hill, watching the clouds streaming through the mountains, let friends and relatives enjoy the BBQ party with a unique outdoor dining table. The green of the trees and gardens with large pond area, all draw a harmonious space with nature extremely unique. Near the resort as blue cavity, copper, stream two .... This is the ideal location for sightseeing trips. Outdoor picnic', 'images/homestay/hanoi10.png'),
('Lotusland Relax House','Ba Dinh, Ha Noi, Viet Nam',7,'Located in Nguyen Truong To Street, the apartment owns a rustic charm with a tranquil space, surrounded by greenery. Stay here, it is very convenient for you to get around and visit Hanoi’s famous tourist attraction. To fulfill our desire to help tourist relax after a long flight or an exciting day of exploration, every corner of the house is carefully furnished. The design is a combination of antique and modern style. Let’s try and experience!','images/homestay/hanoi11.jpg'),

('Fusio Purr lGorgeous','Quan 4, Ho Chi Minh, Viet Nam',2,'Located in a quite alley in a heart of downtown. (1min to access main street) - Fully equipped with queen bed, private bathroom. - Roftop also space where you can have a bit of fresh air & relax after long day. Free cleaning room once per week ( stay over a week). Free washing clothes once per week (stay over a week) Fast wifi We know you have many choices, tks choosing “ FUSION PURRING HOME”. Just a few minute to everywhere. heck-in time after 2PM and check-out time is 12PM (noon). Early check-in and late check-out are subject to our room availability, extra fee might be incurred for late check-out or early check-in requests.','images/homestay/hcm1.jpg'),
('Coral PLAYCATION','Quan 1, Ho Chi Minh, Viet Nam',7,'Stepping out of the apartment, you are already at the heart of Saigon. Welcome to The Playcation - Coral Concept! Our newly renovated 80m2 apartment with 3 bedrooms are perfect for group of friends, family, or couples or loners who want spacious artfully design for their own. The place is right at the central of Saigon, in a very safe area, surrounded by lots of attractive destinations, restaurants, shops,... all can be easily reached on foot or by a short taxi drive. [NEWLY RENOVATED] - 80m2 with 3 bedrooms, 3 bathrooms, 1 bath tub, 1 kitchen, 1 living room with 1 sofa bed - 1 safety lock for each room to keep your valuable belongs - Full amenities: ✔excellent wifi ✔elevator ✔iron ✔washing machine ✔dryer ✔hair dryer ✔Nexflix - In a very safe area [CENTRAL LOCATION] - 2 min walk to Bui Vien walking street - 20 min walk to Ben Thanh market - Less than 10 min taxi or 30 min walk to Nguyen Hue walking street, Notre Dame Cathedral, Saigon Central Post Office, Independence Palace, and Saigon Skydeck - Bitexco Financial Tower. [EASY & CONVENIENT] - Apartment in a building on main street, on 1st floor with elevator - CircleK right in front of the apartment - Supermarket in 5min walk - Surrounded by local shops, cafes and restaurants at the door step - Quite and friendly neighbor - Easy to hang around on foot - Host speaks perfect English - Self check-in.','images/homestay/hcm2.jpg'),
('D’s Alley Eco Homestay','Quan 7, Ho Chi Minh, Viet Nam',8,'D’s Alley Private Eco Home-stay places in Alley 486 on Phan Xich Long street of Phu Nhuan District where we can live, relax and share our live stories! Our home-stay places in quite place which is suitable to relax after a busy daytime. Our rooms are full wooden luxury furniture with private bathroom and so many other utilities such as: air-con,TV, free and strong WiFi, desk and chairs, big chest, kettle, etc. I have a dog and I considers him as our family member, our place also welcome pet owner.','images/homestay/hanoi11.jpg'),
('Simple Home Tourist','Quan 1, Ho Chi Minh, Viet Nam',1,'24/7 access with key cards. The apartment is all yours to use. Please make yourself at home. I’m here for you during your stay, but the level of interaction is up to you. I’m only a phone call or message away. You will be able to self-check in upon arrival. The Alley is quite small, the taxi stops about 20 meters from my place and you will need to walk in.','images/homestay/hcm4.jpg'),
('Sunlit Studio','Quan 7, Ho Chi Minh, Viet Nam',1,'An incredibly spacious sleek studio located in Phan Xich Long street - one of the most iconic streets of Saigon, literally walking distance from many local restaurants and cafes. The studio has a large balcony which gives you a sweeping view over the "organized chaos" traffic of Saigon while enjoying your favorite drink. This bright and airy accommodation will give you the complete comfort and relaxation whether you are staying for work or after a long day of exploring the buzzing city. My stand-alone studio is a part of 2-unit newly renovated building. This also features little photogenic corners filled with natural sunlight for all you travelstagram lovers, and a well-equipped kitchen where you can find our signature complimentary coffee and tea bar. The design is comprised of unique Vietnamese vernacular style featuring high quality furniture and decent craftsmanship. Walking down to the ground floor, you will find yourself on a main road that leads to scrumptious dining places and everything you need in just minutes of walking.','images/homestay/hcm5.png'),
('Staycious Home 1C','Quan 1, Ho Chi Minh, Viet Nam',10,'Conveniently located in the prime location of Ho Chi Minh City, Staycious offers easy access to the city’s famous attractions, shopping centers and commercial buildings. Conveniently located in the prime location of Ho Chi Minh City, Staycious offers easy access to the city’s famous attractions, shopping centers and commercial buildings. Staycious Homestay is located in Ho Chi Minh City, 200 meters from Ben Thanh Market. It is also a 3-minute walk from Takashimaya Vietnam and a 2-minute walk from Mong Bridge. - 7m from Nguyen Hue Street, Bitexco. + Roof top overlooking Bitexco. Safe and secure (external door lock, with digital door lock inside). + Spacious and beautifully designed. + Full kitchen + Wi-Fi hotspot, high speed internet. Visitors You will have 24/7 self-access, no curfew.','images/homestay/hcm6.jpg'),
('Skytel Homestay','Quan 1, Ho Chi Minh, Viet Nam',10,'Located on a quiet street, close to the well-known walking Bui Vien street. Our home welcome all the guests from over the world, a brand new place for you to relax after an explore day in our city and a quiet night after partying.','images/homestay/hcm7.jpg'),
('Cozrum Homes','Quan 3, Ho Chi Minh, Viet Nam',9,'New Condominium located in an alley District 3 which is super convenient for you to get to other corners of this vibrant city but away from the noisy streets of Sai Gon. It takes you only 5 mins to get to the oldest market and church in town as well as the ancient pagoda named “ Ngoc Hoang” which means “God”.It is 10 mins from Notre Dame Cathedral – the heart of this city and 10 mins from the airport. This place is the intersection of 4 districts: 1,3, Phu Nhuan and Binh Thanh. Hundreds of restaurants, spa, fashion shops, bars are in walking distance. The best choice when you visit Saigon.','images/homestay/hcm8.jpg'),
('Salato Modern Studio 5','Quan 4, Ho Chi Minh, Viet Nam',9,'Studio 20F offers incredible view of old saigon town and a river. This is a modern studio with a smart queen-size bed, a cable TV, Wifi, full kitchenette and toiletries in a brand new residential building near Ong Lanh Bridge. Infinitive swimming pool and fully equipped GYM are inclusive. All tourist attractions are super close. Don’t worry if you are too tired or lazy to go out for dining, we have a fully equipped kitchenette for you super star dishes. Have us mentioned the GYM, yoga room and infinitive pool? There are some yoga classes from time to time.','images/homestay/hcm9.jpg'),
('Bright Furnished Place','Quan 4, Ho Chi Minh, Viet Nam',4,'Studio 20F offers incredible view of old saigon town and a river. This is a modern studio with a smart queen-size bed, a cable TV, Wifi, full kitchenette and toiletries in a brand new residential building near Ong Lanh Bridge. Infinitive swimming pool and fully equipped GYM are inclusive. All tourist attractions are super close. Don’t worry if you are too tired or lazy to go out for dining, we have a fully equipped kitchenette for you super star dishes. Have us mentioned the GYM, yoga room and infinitive pool? There are some yoga classes from time to time.','images/homestay/hcm10.jpg'),

('Vung Tau Home 2', 'Ba Ria, Vung Tau, Viet Nam', 2, 'The apartment is located in an ideal location, this place is a crowded street of the foreign community. There are many restaurants, bars, cafes, gyms, all made for foreigners. The surrounding area has many beautiful landscapes such as Ho Kiem, Ho Truc Bach, Quan Thanh Pagoda, Red River, Quang An Flower Village, Nhat Tan Flower Village and especially large and large West Lake, where you can go. Bicycles (free of charge) around the lake and coffee along the way. Contrary to the bustle of the street, the apartment is located in an alley about 100 meters from the street, very quiet and suitable for rest, work and live here. You will feel comfortable because the Host is very friendly and hospitable. Safe house with 24/24 security. You can enjoy cycling around town with free bicycles. Free housekeeping service twice a week, parking motorbike in the building.','images/homestay/vungtau1.jpg'),
('Indochina Style Duplex', 'Ba Ria, Vung Tau, Viet Nam', 8, 'Welcome to MLIBRARY - The most luxurious apartment experience in Hanoi. MLIBRARY bring you the style that hasn’t been seen anywhere in Vietnam. Located in Tay Ho district with enormous view of West Lake and The Red River. “ We do not build a homestay, we develop a living space with a lot of emotion”', 'images/homestay/vungtau2.jpg'),
('Queen’s Apartment', 'Ba Ria, Vung Tau, Viet Nam', 4, 'Guests can enjoy free access to street, European and Asian dishes around King’s Apartment area. New and modern apartment’s just furnished with conveniences to help customers feel like home. The whole apartment is full of natural light, creating both airy and spacious. The buildings has full amenities includes Gym, 4 season swimming pool, nice garden, restaurants, kid play areas, Pharmacy shop... Traffic is very convenient to go anywhere in the city.', 'images/homestay/vungtau3.jpg'),
('CASSABELLA Homestay', 'Ba Ria, Vung Tau, Viet Nam', 2, 'Located at No.18, Dich Vong Hau Street in the center of Cau Giay District where is a new modern urban of Hanoi, it would be pretty convenient for you to approach the hotel from where you are. With 45 well-equipped & fully furnished rooms, Bao Hung Hotel & Apartment is now one of the biggest in Cau Giay district. with a fully equipped shared kitchen (magnetic stove, refrigerator, microwave, BBQ, water heater, ...) you have cook your own favorite food and organize a memorable BBQ party when you come to Mint.', 'images/homestay/vungtau4.jpg'),
('Lici Homestay','Ba Ria, Vung Tau, Viet Nam', 3, 'Lii’s Homestay is a homestay located in the heart of Hanoi, next to the West Lake. Lii’s Homestay aims to the natural elements in the living space, we always take care of every smallest decor in the room. We take care of our customers like family members. Lii’s Homestay is very quiet. Just 5 minutes away, you will reach West Lake. Come to us today. with a fully equipped shared kitchen (magnetic stove, refrigerator, microwave, BBQ, water heater, ...) you have cook your own favorite food and organize a memorable BBQ party when you come to Mint.', 'images/homestay/vungtau5.jpg'),
('Watermelon treehouse', 'Ba Ria, Vung Tau, Viet Nam', 8, 'Does the bustling city drive you nuts sometimes? Do you feel short of me-time? Longing for new energy? Wondering what is life on a tree with leaves and bees? We offer you the OKia Treehouse for a wonderful get-away trip & all the best thrills nature can bring. Only 40 minutes drive from Hanoi, your family, your kids or your group of friends will reach the Treehouse. Here we proudly bring you very personalized experience so you can get all the “sensory” that you need for a better “you” or a better relationship with your buddies. OKia Treehouse is an invitation to self-soothe and to bring people closer – what is really important in this “fast-food” world.', 'images/homestay/vungtau6.jpg'),
('Vinhomes GreenBay','Ba Ria, Vung Tau, Viet Nam', 7, 'New and modern apartment’s just furnished with conveniences to help customers feel like home. The whole apartment is full of natural light, creating both airy and spacious. The buildings has full amenities includes Gym, 4 season swimming pool, nice garden, restaurants, kid play areas, Pharmacy shop... Traffic is very convenient to go anywhere in the city as well as industrial parks around the capital Ha Noi.', 'images/homestay/vungtau7.jpg'),
('Zen Mediation House', 'Ba Ria, Vung Tau, Viet Nam', 7, 'Pictures speak a thousands words. This beautiful and unique Tree House is among one of Seven Wonder Houses built by artist Dao Anh Khanh - a leading Vietnamese Artist, known for his famous dance performance and contemporary arts. with a fully equipped shared kitchen (magnetic stove, refrigerator, microwave, BBQ, water heater, ...) you have cook your own favorite food and organize a memorable BBQ party when you come to Mint.', 'images/homestay/vungtau8.jpg'),
('Langmandi Homestay', 'Ba Ria, Vung Tau, Viet Nam', 2, 'A well-equipped room located on Hanoi’s famous central street, 1 km from Hoan Kiem Lake. Lots of best restaurants and famous food around here. Its also very close to Vincom Center-the most famous shopping. You just need to walk. There is a nice balcony for you to enjoy tea or coffee every morning and a romantic dinner with friends. Would be a great experience with city view. with a fully equipped shared kitchen (magnetic stove, refrigerator, microwave, BBQ, water heater, ...) you have cook your own favorite food and organize a memorable BBQ party when you come to Mint.', 'images/homestay/vungtau9.jpg'),
('Cloudy View Villa', 'Ba Ria, Vung Tau, Viet Nam', 9, 'Leaving the noisy and crowded city to find a private living space that is airy, peaceful in the water, plants and sunshine with CLOUDY VIEW - Ba Vi. With a modern swimming pool, overlooking the green tea hill, watching the clouds streaming through the mountains, let friends and relatives enjoy the BBQ party with a unique outdoor dining table. The green of the trees and gardens with large pond area, all draw a harmonious space with nature extremely unique. Near the resort as blue cavity, copper, stream two .... This is the ideal location for sightseeing trips. Outdoor picnic', 'images/homestay/vungtau10.jpg'),
('Victory Penthouse','Ba Ria, Vung Tau, Viet Nam',10,'The penthouse owns a rustic charm with a tranquil space, surrounded by greenery. Stay here, it is very convenient for you to get around and visit Hanoi’s famous tourist attraction. To fulfill our desire to help tourist relax after a long flight or an exciting day of exploration, every corner of the house is carefully furnished. The design is a combination of antique and modern style. Let’s try and experience!','images/homestay/vungtau11.jpg'),

('Mayli Homestay Dalat','Da Lat, Lam Dong, Viet Nam',2,'Located in a quite alley in a heart of downtown. (1min to access main street) - Fully equipped with queen bed, private bathroom. - Roftop also space where you can have a bit of fresh air & relax after long day. Free cleaning room once per week ( stay over a week). Free washing clothes once per week (stay over a week) Fast wifi We know you have many choices, tks choosing “ FUSION PURRING HOME”. Just a few minute to everywhere. heck-in time after 2PM and check-out time is 12PM (noon). Early check-in and late check-out are subject to our room availability, extra fee might be incurred for late check-out or early check-in requests.','images/homestay/dalat1.png'),
('Coral PLAYCATION','Da Lat, Lam Dong, Viet Nam',7,'Stepping out of the apartment, you are already at the heart of Saigon. Welcome to The Playcation - Coral Concept! Our newly renovated 80m2 apartment with 3 bedrooms are perfect for group of friends, family, or couples or loners who want spacious artfully design for their own. The place is right at the central of Saigon, in a very safe area, surrounded by lots of attractive destinations, restaurants, shops,... all can be easily reached on foot or by a short taxi drive. [NEWLY RENOVATED] - 80m2 with 3 bedrooms, 3 bathrooms, 1 bath tub, 1 kitchen, 1 living room with 1 sofa bed - 1 safety lock for each room to keep your valuable belongs - Full amenities: ✔excellent wifi ✔elevator ✔iron ✔washing machine ✔dryer ✔hair dryer ✔Nexflix - In a very safe area [CENTRAL LOCATION] - 2 min walk to Bui Vien walking street - 20 min walk to Ben Thanh market - Less than 10 min taxi or 30 min walk to Nguyen Hue walking street, Notre Dame Cathedral, Saigon Central Post Office, Independence Palace, and Saigon Skydeck - Bitexco Financial Tower. [EASY & CONVENIENT] - Apartment in a building on main street, on 1st floor with elevator - CircleK right in front of the apartment - Supermarket in 5min walk - Surrounded by local shops, cafes and restaurants at the door step - Quite and friendly neighbor - Easy to hang around on foot - Host speaks perfect English - Self check-in.','images/homestay/dalat2.jpg'),
('D’s Alley Luxury Room','Da Lat, Lam Dong, Viet Nam',6,'D’s Alley Private Eco Home-stay places in Alley 486 on Phan Xich Long street of Phu Nhuan District where we can live, relax and share our live stories! Our home-stay places in quite place which is suitable to relax after a busy daytime. Our rooms are full wooden luxury furniture with private bathroom and so many other utilities such as: air-con,TV, free and strong WiFi, desk and chairs, big chest, kettle, etc. I have a dog and I considers him as our family member, our place also welcome pet owner.','images/homestay/dalat3.jpg'),
('Simple Home Tourist','Da Lat, Lam Dong, Viet Nam',1,'24/7 access with key cards. The apartment is all yours to use. Please make yourself at home. I’m here for you during your stay, but the level of interaction is up to you. I’m only a phone call or message away. You will be able to self-check in upon arrival. The Alley is quite small, the taxi stops about 20 meters from my place and you will need to walk in.','images/homestay/dalat4.jpg'),
('Sunlit Studio','Da Lat, Lam Dong, Viet Nam',1,'An incredibly spacious sleek studio located in Phan Xich Long street - one of the most iconic streets of Saigon, literally walking distance from many local restaurants and cafes. The studio has a large balcony which gives you a sweeping view over the "organized chaos" traffic of Saigon while enjoying your favorite drink. This bright and airy accommodation will give you the complete comfort and relaxation whether you are staying for work or after a long day of exploring the buzzing city. My stand-alone studio is a part of 2-unit newly renovated building. This also features little photogenic corners filled with natural sunlight for all you travelstagram lovers, and a well-equipped kitchen where you can find our signature complimentary coffee and tea bar. The design is comprised of unique Vietnamese vernacular style featuring high quality furniture and decent craftsmanship. Walking down to the ground floor, you will find yourself on a main road that leads to scrumptious dining places and everything you need in just minutes of walking.','images/homestay/dalat5.jpg'),
('Staycious Home 1C','Da Lat, Lam Dong, Viet Nam',5,'Conveniently located in the prime location of Ho Chi Minh City, Staycious offers easy access to the city’s famous attractions, shopping centers and commercial buildings. Conveniently located in the prime location of Ho Chi Minh City, Staycious offers easy access to the city’s famous attractions, shopping centers and commercial buildings. Staycious Homestay is located in Ho Chi Minh City, 200 meters from Ben Thanh Market. It is also a 3-minute walk from Takashimaya Vietnam and a 2-minute walk from Mong Bridge. - 7m from Nguyen Hue Street, Bitexco. + Roof top overlooking Bitexco. Safe and secure (external door lock, with digital door lock inside). + Spacious and beautifully designed. + Full kitchen + Wi-Fi hotspot, high speed internet. Visitors You will have 24/7 self-access, no curfew.','images/homestay/dalat6.jpg'),
('Skytel Homestay','Da Lat, Lam Dong, Viet Nam',5,'Located on a quiet street, close to the well-known walking Bui Vien street. Our home welcome all the guests from over the world, a brand new place for you to relax after an explore day in our city and a quiet night after partying. with a fully equipped shared kitchen (magnetic stove, refrigerator, microwave, BBQ, water heater, ...) you have cook your own favorite food and organize a memorable BBQ party when you come to Mint.','images/homestay/dalat7.jpg'),
('Cozrum Homes','Da Lat, Lam Dong, Viet Nam',9,'New Condominium located in an alley District 3 which is super convenient for you to get to other corners of this vibrant city but away from the noisy streets of Sai Gon. It takes you only 5 mins to get to the oldest market and church in town as well as the ancient pagoda named “ Ngoc Hoang” which means “God”.It is 10 mins from Notre Dame Cathedral – the heart of this city and 10 mins from the airport. This place is the intersection of 4 districts: 1,3, Phu Nhuan and Binh Thanh. Hundreds of restaurants, spa, fashion shops, bars are in walking distance. The best choice when you visit Saigon.','images/homestay/dalat8.jpg'),
('Salato Modern Studio 5','Da Lat, Lam Dong, Viet Namm',9,'Studio 20F offers incredible view of old saigon town and a river. This is a modern studio with a smart queen-size bed, a cable TV, Wifi, full kitchenette and toiletries in a brand new residential building near Ong Lanh Bridge. Infinitive swimming pool and fully equipped GYM are inclusive. All tourist attractions are super close. Don’t worry if you are too tired or lazy to go out for dining, we have a fully equipped kitchenette for you super star dishes. Have us mentioned the GYM, yoga room and infinitive pool? There are some yoga classes from time to time.','images/homestay/dalat9.jpg'),
('Bright Furnished Place','Da Lat, Lam Dong, Viet Nam',4,'Studio 20F offers incredible view of old saigon town and a river. This is a modern studio with a smart queen-size bed, a cable TV, Wifi, full kitchenette and toiletries in a brand new residential building near Ong Lanh Bridge. Infinitive swimming pool and fully equipped GYM are inclusive. All tourist attractions are super close. Don’t worry if you are too tired or lazy to go out for dining, we have a fully equipped kitchenette for you super star dishes. Have us mentioned the GYM, yoga room and infinitive pool? There are some yoga classes from time to time.','images/homestay/dalat10.jpg'),

('Fusio Purr Downtown','Cam Le, Da Nang, Viet Nam',2,'Located in a quite alley in a heart of downtown. (1min to access main street) - Fully equipped with queen bed, private bathroom. - Roftop also space where you can have a bit of fresh air & relax after long day. Free cleaning room once per week ( stay over a week). Free washing clothes once per week (stay over a week) Fast wifi We know you have many choices, tks choosing “ FUSION PURRING HOME”. Just a few minute to everywhere. heck-in time after 2PM and check-out time is 12PM (noon). Early check-in and late check-out are subject to our room availability, extra fee might be incurred for late check-out or early check-in requests.','images/homestay/danang1.jpg'),
('Coral PLAYCATION','Cam Le, Da Nang, Viet Nam',7,'Stepping out of the apartment, you are already at the heart of Saigon. Welcome to The Playcation - Coral Concept! Our newly renovated 80m2 apartment with 3 bedrooms are perfect for group of friends, family, or couples or loners who want spacious artfully design for their own. The place is right at the central of Saigon, in a very safe area, surrounded by lots of attractive destinations, restaurants, shops,... all can be easily reached on foot or by a short taxi drive. [NEWLY RENOVATED] - 80m2 with 3 bedrooms, 3 bathrooms, 1 bath tub, 1 kitchen, 1 living room with 1 sofa bed - 1 safety lock for each room to keep your valuable belongs - Full amenities: ✔excellent wifi ✔elevator ✔iron ✔washing machine ✔dryer ✔hair dryer ✔Nexflix - In a very safe area [CENTRAL LOCATION] - 2 min walk to Bui Vien walking street - 20 min walk to Ben Thanh market - Less than 10 min taxi or 30 min walk to Nguyen Hue walking street, Notre Dame Cathedral, Saigon Central Post Office, Independence Palace, and Saigon Skydeck - Bitexco Financial Tower. [EASY & CONVENIENT] - Apartment in a building on main street, on 1st floor with elevator - CircleK right in front of the apartment - Supermarket in 5min walk - Surrounded by local shops, cafes and restaurants at the door step - Quite and friendly neighbor - Easy to hang around on foot - Host speaks perfect English - Self check-in.','images/homestay/danang2.jpg'),
('D’s Alley Eco Homestay','Cam Le, Da Nang, Viet Nam',8,'D’s Alley Private Eco Home-stay places in Alley 486 on Phan Xich Long street of Phu Nhuan District where we can live, relax and share our live stories! Our home-stay places in quite place which is suitable to relax after a busy daytime. Our rooms are full wooden luxury furniture with private bathroom and so many other utilities such as: air-con,TV, free and strong WiFi, desk and chairs, big chest, kettle, etc. I have a dog and I considers him as our family member, our place also welcome pet owner.','images/homestay/danang3.png'),
('Simple Home Tourist','My An, Da Nang, Viet Nam',6,'24/7 access with key cards. The apartment is all yours to use. Please make yourself at home. I’m here for you during your stay, but the level of interaction is up to you. I’m only a phone call or message away. You will be able to self-check in upon arrival. The Alley is quite small, the taxi stops about 20 meters from my place and you will need to walk in.','images/homestay/danang4.jpg'),
('Sunlit Studio','Hoa Vang, Da Nang, Viet Nam',6,'An incredibly spacious sleek studio located in Phan Xich Long street - one of the most iconic streets of Saigon, literally walking distance from many local restaurants and cafes. The studio has a large balcony which gives you a sweeping view over the "organized chaos" traffic of Saigon while enjoying your favorite drink. This bright and airy accommodation will give you the complete comfort and relaxation whether you are staying for work or after a long day of exploring the buzzing city. My stand-alone studio is a part of 2-unit newly renovated building. This also features little photogenic corners filled with natural sunlight for all you travelstagram lovers, and a well-equipped kitchen where you can find our signature complimentary coffee and tea bar. The design is comprised of unique Vietnamese vernacular style featuring high quality furniture and decent craftsmanship. Walking down to the ground floor, you will find yourself on a main road that leads to scrumptious dining places and everything you need in just minutes of walking.','images/homestay/danang5.jpg'),
('Staycious Home 1C','My An, Da Nang, Viet Nam',3,'Conveniently located in the prime location of Ho Chi Minh City, Staycious offers easy access to the city’s famous attractions, shopping centers and commercial buildings. Conveniently located in the prime location of Ho Chi Minh City, Staycious offers easy access to the city’s famous attractions, shopping centers and commercial buildings. Staycious Homestay is located in Ho Chi Minh City, 200 meters from Ben Thanh Market. It is also a 3-minute walk from Takashimaya Vietnam and a 2-minute walk from Mong Bridge. - 7m from Nguyen Hue Street, Bitexco. + Roof top overlooking Bitexco. Safe and secure (external door lock, with digital door lock inside). + Spacious and beautifully designed. + Full kitchen + Wi-Fi hotspot, high speed internet. Visitors You will have 24/7 self-access, no curfew.','images/homestay/danang6.jpg'),
('Skytel Homestay','My Khe, Da Nang, Viet Nam',2,'Located on a quiet street, close to the well-known walking Bui Vien street. Our home welcome all the guests from over the world, a brand new place for you to relax after an explore day in our city and a quiet night after partying. with a fully equipped shared kitchen (magnetic stove, refrigerator, microwave, BBQ, water heater, ...) you have cook your own favorite food and organize a memorable BBQ party when you come to Mint.','images/homestay/danang7.jpg'),
('Cozrum Homes','My An, Da Nang, Viet Nam',2,'New Condominium located in an alley District 3 which is super convenient for you to get to other corners of this vibrant city but away from the noisy streets of Sai Gon. It takes you only 5 mins to get to the oldest market and church in town as well as the ancient pagoda named “ Ngoc Hoang” which means “God”.It is 10 mins from Notre Dame Cathedral – the heart of this city and 10 mins from the airport. This place is the intersection of 4 districts: 1,3, Phu Nhuan and Binh Thanh. Hundreds of restaurants, spa, fashion shops, bars are in walking distance. The best choice when you visit Saigon.','images/homestay/danang8.jpg'),
('Salato Modern Studio 5','My An, Da Nang, Viet Nam',9,'Studio 20F offers incredible view of old saigon town and a river. This is a modern studio with a smart queen-size bed, a cable TV, Wifi, full kitchenette and toiletries in a brand new residential building near Ong Lanh Bridge. Infinitive swimming pool and fully equipped GYM are inclusive. All tourist attractions are super close. Don’t worry if you are too tired or lazy to go out for dining, we have a fully equipped kitchenette for you super star dishes. Have us mentioned the GYM, yoga room and infinitive pool? There are some yoga classes from time to time.','images/homestay/danang9.jpg'),
('Fully Furnished Place','Son Tra, Da Nang, Viet Nam',4,'Studio 20F offers incredible view of old saigon town and a river. This is a modern studio with a smart queen-size bed, a cable TV, Wifi, full kitchenette and toiletries in a brand new residential building near Ong Lanh Bridge. Infinitive swimming pool and fully equipped GYM are inclusive. All tourist attractions are super close. Don’t worry if you are too tired or lazy to go out for dining, we have a fully equipped kitchenette for you super star dishes. Have us mentioned the GYM, yoga room and infinitive pool? There are some yoga classes from time to time.','images/homestay/danang10.jpg'),

('Wild Sea Apartment','Loc Tho, Nha Trang, Viet Nam',2,'Located in a quite alley in a heart of downtown. (1min to access main street) - Fully equipped with queen bed, private bathroom. - Roftop also space where you can have a bit of fresh air & relax after long day. Free cleaning room once per week ( stay over a week). Free washing clothes once per week (stay over a week) Fast wifi We know you have many choices, tks choosing “ FUSION PURRING HOME”. Just a few minute to everywhere. heck-in time after 2PM and check-out time is 12PM (noon). Early check-in and late check-out are subject to our room availability, extra fee might be incurred for late check-out or early check-in requests.','images/homestay/nhatrang1.jpg'),
('Coral PLAYCATION','Tan Lap, Nha Trang, Viet Nam',7,'Stepping out of the apartment, you are already at the heart of Saigon. Welcome to The Playcation - Coral Concept! Our newly renovated 80m2 apartment with 3 bedrooms are perfect for group of friends, family, or couples or loners who want spacious artfully design for their own. The place is right at the central of Saigon, in a very safe area, surrounded by lots of attractive destinations, restaurants, shops,... all can be easily reached on foot or by a short taxi drive. [NEWLY RENOVATED] - 80m2 with 3 bedrooms, 3 bathrooms, 1 bath tub, 1 kitchen, 1 living room with 1 sofa bed - 1 safety lock for each room to keep your valuable belongs - Full amenities: ✔excellent wifi ✔elevator ✔iron ✔washing machine ✔dryer ✔hair dryer ✔Nexflix - In a very safe area [CENTRAL LOCATION] - 2 min walk to Bui Vien walking street - 20 min walk to Ben Thanh market - Less than 10 min taxi or 30 min walk to Nguyen Hue walking street, Notre Dame Cathedral, Saigon Central Post Office, Independence Palace, and Saigon Skydeck - Bitexco Financial Tower. [EASY & CONVENIENT] - Apartment in a building on main street, on 1st floor with elevator - CircleK right in front of the apartment - Supermarket in 5min walk - Surrounded by local shops, cafes and restaurants at the door step - Quite and friendly neighbor - Easy to hang around on foot - Host speaks perfect English - Self check-in.','images/homestay/nhatrang2.jpg'),
('D’s Alley Eco Homestay','Tan Lap, Nha Trang, Viet Nam',8,'D’s Alley Private Eco Home-stay places in Alley 486 on Phan Xich Long street of Phu Nhuan District where we can live, relax and share our live stories! Our home-stay places in quite place which is suitable to relax after a busy daytime. Our rooms are full wooden luxury furniture with private bathroom and so many other utilities such as: air-con,TV, free and strong WiFi, desk and chairs, big chest, kettle, etc. I have a dog and I considers him as our family member, our place also welcome pet owner.','images/homestay/nhatrang3.jpg'),
('Simple Home Tourist','Loc Tho, Nha Trang, Viet Nam',1,'24/7 access with key cards. The apartment is all yours to use. Please make yourself at home. I’m here for you during your stay, but the level of interaction is up to you. I’m only a phone call or message away. You will be able to self-check in upon arrival. The Alley is quite small, the taxi stops about 20 meters from my place and you will need to walk in.','images/homestay/nhatrang4.jpg'),
('Sunlit Studio','Loc Tho, Nha Trang, Viet Nam',4,'An incredibly spacious sleek studio located in Phan Xich Long street - one of the most iconic streets of Saigon, literally walking distance from many local restaurants and cafes. The studio has a large balcony which gives you a sweeping view over the "organized chaos" traffic of Saigon while enjoying your favorite drink. This bright and airy accommodation will give you the complete comfort and relaxation whether you are staying for work or after a long day of exploring the buzzing city. My stand-alone studio is a part of 2-unit newly renovated building. This also features little photogenic corners filled with natural sunlight for all you travelstagram lovers, and a well-equipped kitchen where you can find our signature complimentary coffee and tea bar. The design is comprised of unique Vietnamese vernacular style featuring high quality furniture and decent craftsmanship. Walking down to the ground floor, you will find yourself on a main road that leads to scrumptious dining places and everything you need in just minutes of walking.','images/homestay/nhatrang5.jpg'),
('MINT HOMESTAY','Loc Tho, Nha Trang, Viet Nam',7,'MINT HOMESTAY NHA TRANG is a beautiful little house located in the beautiful coastal city of Nha Trang. With 8 bedrooms, all room have beautifully decorated,fresh colors, giving you a feeling comfortably and easily when coming to Mint Homestay. Mint Homestay - Deluxe Double Room is a 25m2 room, beautifully designed, with elegant colors, window facing the yard will make you feel comfortable.','images/homestay/nhatrang6.jpg'),
('Skytel Homestay','Tan Lap, Nha Trang, Viet Nam',7,'Located on a quiet street, close to the well-known walking Bui Vien street. Our home welcome all the guests from over the world, a brand new place for you to relax after an explore day in our city and a quiet night after partying. with a fully equipped shared kitchen (magnetic stove, refrigerator, microwave, BBQ, water heater, ...) you have cook your own favorite food and organize a memorable BBQ party when you come to Mint.','images/homestay/nhatrang7.jpg'),
('MOONLIGHT HOUSE','Vinh Tho, Nha Trang, Viet Nam',9,'New Condominium located in an alley District 3 which is super convenient for you to get to other corners of this vibrant city but away from the noisy streets of Sai Gon. It takes you only 5 mins to get to the oldest market and church in town as well as the ancient pagoda named “ Ngoc Hoang” which means “God”.It is 10 mins from Notre Dame Cathedral – the heart of this city and 10 mins from the airport. This place is the intersection of 4 districts: 1,3, Phu Nhuan and Binh Thanh. Hundreds of restaurants, spa, fashion shops, bars are in walking distance. The best choice when you visit Saigon.','images/homestay/nhatrang8.jpg'),
('Salato Modern Studio 5','Vinh Tho, Nha Trang, Viet Nam',9,'Studio 20F offers incredible view of old saigon town and a river. This is a modern studio with a smart queen-size bed, a cable TV, Wifi, full kitchenette and toiletries in a brand new residential building near Ong Lanh Bridge. Infinitive swimming pool and fully equipped GYM are inclusive. All tourist attractions are super close. Don’t worry if you are too tired or lazy to go out for dining, we have a fully equipped kitchenette for you super star dishes. Have us mentioned the GYM, yoga room and infinitive pool? There are some yoga classes from time to time.','images/homestay/nhatrang9.jpg'),
('Bright Furnished Place','Tan Lap, Nha Trang, Viet Nam',5,'Studio 20F offers incredible view of old saigon town and a river. This is a modern studio with a smart queen-size bed, a cable TV, Wifi, full kitchenette and toiletries in a brand new residential building near Ong Lanh Bridge. Infinitive swimming pool and fully equipped GYM are inclusive. All tourist attractions are super close. Don’t worry if you are too tired or lazy to go out for dining, we have a fully equipped kitchenette for you super star dishes. Have us mentioned the GYM, yoga room and infinitive pool? There are some yoga classes from time to time.','images/homestay/nhatrang10.jpg')
GO

INSERT INTO [dbo].[Customer]
           ([Name]
           ,[Gender]
           ,[DOB]
           ,[Phone]
           ,[Email])
VALUES
('Admin',0,'2001-08-27','0395117155','admin@gmail.com'),
('Guest',1,'2002-09-14','0912442488','guest@gmail.com')
GO

INSERT INTO [dbo].[Account]
           ([username]
           ,[password]
           ,[Type]
           ,[CustomerID])
VALUES
('admin','admin',1,1),
('guest','guest',0,2)
GO